# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  tls_insecure_skip_verify:
    description: |
      Flag to skip the verification for insecure TLS.
      If "true", self-signed certs can be seamlessly used; this setting
      will be applied to all of the Agent configurations (Prometheus,
      Loki).
    type: boolean
    default: false
  always_enable_zipkin:
    description: > 
      Force-enable the receiver for the 'zipkin' protocol in Grafana Agent, 
      even if there is no integration currently requesting it.
    type: boolean
    default: false
  always_enable_otlp_grpc:
    description: > 
      Force-enable the receiver for the 'otlp_grpc' protocol in Grafana Agent, 
      even if there is no integration currently requesting it.
    type: boolean
    default: false
  always_enable_otlp_http:
    description: > 
      Force-enable the receiver for the 'otlp_http' protocol in Grafana Agent, 
      even if there is no integration currently requesting it.
    type: boolean
    default: false
  always_enable_jaeger_grpc:
    description: > 
      Force-enable the receiver for the 'jaeger_grpc' protocol in Grafana Agent, 
      even if there is no integration currently requesting it.
    type: boolean
    default: false
  always_enable_jaeger_thrift_http:
    description: >
      Force-enable the receiver for the 'jaeger_thrift_http' protocol in Grafana Agent, 
      even if there is no integration currently requesting it.
    type: boolean
    default: false
  charm_traces_sampling_percentage:
    description: >
      This property defines the percentage of charm traces that are sent to tracing backend.
      Setting it to 100 would mean all charm traces are kept, setting to 0 means charm traces
      aren't sent to tracing backend at all.
    type: float
    default: 100.0
  workload_traces_sampling_percentage:
    description: >
      This property defines the percentage of workload traces that are sent to tracing backend.
      Setting it to 100 would mean all workload traces are kept, setting to 0 means workload traces
      aren't sent to tracing backend at all.
    type: float
    default: 1.0
  error_traces_sampling_percentage:
    description: >
      This property defines the percentage of error traces (regardless of the type) that are sent to tracing backend.
      Setting it to 100 would mean all error traces are kept, setting to 0 means error traces
      aren't sent to tracing backend at all.
    type: float
    default: 100.0
