# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

name: grafana-agent-k8s

description: |
  Grafana Agent for Kubernetes cluster
summary: |
  Grafana Agent is a telemetry collector for sending metrics, logs, and trace data to the opinionated Grafana observability stack.
maintainers:
    - Jose Massón <jose.masson@canonical.com>
    - Ryan Barry <ryan.barry@canonical.com>
    - Leon Mintz <leon.mintz@canonical.com>
    - Pietro Pasotti <pietro.pasotti@canonical.com>
    - Dylan Stephano-Shachter <dylan.stephano-shachter@canonical.com>
    - Luca Bello <luca.bello@canonical.com>
    - Simon Aronsson <simon.aronsson@canonical.com>
assumes:
  - k8s-api

docs: https://discourse.charmhub.io/t/grafana-agent-k8s-docs-index/5605
website: https://charmhub.io/grafana-agent-k8s
source: https://github.com/canonical/grafana-agent-k8s-operator
issues: https://github.com/canonical/grafana-agent-k8s-operator/issues

containers:
  agent:
    resource: agent-image
    mounts:
      - storage: data
        location: /tmp/agent/data

resources:
  agent-image:
    type: oci-image
    upstream-source: ghcr.io/canonical/grafana-agent:latest
    description: OCI image for Grafana Agent

requires:
  send-remote-write:
    interface: prometheus_remote_write
  metrics-endpoint:
    interface: prometheus_scrape
  logging-consumer:
    interface: loki_push_api
  grafana-dashboards-consumer:
    interface: grafana_dashboard
  grafana-cloud-config:
    interface: grafana_cloud_config
    limit: 1

provides:
  logging-provider:
    interface: loki_push_api
  grafana-dashboards-provider:
    interface: grafana_dashboard

storage:
  data:
    type: filesystem
