name: Promote Machine Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote
    uses: canonical/observability/.github/workflows/promote-charm.yaml@main
    with:
      charm-path: "machine"
      promotion: ${{ github.event.inputs.promotion }}
    secrets: inherit
