name: Release Libraries

on:
  push:
    branches:
      - main

jobs:
  release-libs:
    uses: canonical/observability/.github/workflows/release-libs.yaml@main
    secrets: inherit
    with:
      # Currently, only the machine charm has libraries
      charm-path: "machine"
